name: Copy light module into production
on:
  push:
    tags:
      - '*'  # Trigger on any tag
jobs:
  copy_to_target:
    name: Copy Integrated light module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: copy file via ssh key (author)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          target: "/magnolia/magnolia-6.3.9/apache-tomcat-9.0.105/webapps/magnoliaAuthor/modules/int-module"
          source: "*"

      - name: copy file via ssh key (publish)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          target: "/magnolia/magnolia-6.3.9/apache-tomcat-9.0.105/webapps/magnoliaPublic/modules/int-module"
          source: "*"
          